### ISSUE TITLE
Implementar suporte para JSON

### ISSUE THREAD

**Issue by evertonagilar** [PPCA2014/ppca_soa#14]
Tarefa: Implementar suporte para JSON

Objetivo: Nosso barramento vai enviar e receber JSON nas requisições. É preciso incluir suporte para as conversões dos tipos Erlang para JSON e vice versa.

Material de referência: 
    - http://www.erlang.org/eeps/eep-0018.html
    - https://github.com/talentdeficit/jsx

Algumas libs que verifiquei possui métdos como este:

atom_to_json(atom) -> string json
json_to_atom(string) -> atom

O módulo ppca_util.erl é o local apropriado para estas funções.

Prioridade: Alta

**Comment by Elliene** [comment]
Everton, criei um arquivo rebar.config que tem a dependência da biblioteca jiffy que você falou.

**Comment by Elliene** [comment]
com essa configuração tem que dar o comando rebar deps para baixar as dependências

**Comment by evertonagilar** [comment]
Eliene, alterei o start_server.bat para passar o path onde está as bibliotecas. Testa ai.

**Comment by Elliene** [comment]
não esto estou conseguindo chamar a biblioteca.

**Comment by evertonagilar** [comment]
Configurei o start_server.sh e start_server.bat para saber onde está as libs. Agora vai!!!

**Comment by evertonagilar** [comment]
Comentei a dependencia da lib json pois vai precisar de um compilador C e quem está usando Windows não vai conseguir compilar.

**Comment by evertonagilar** [comment]
Suporte implementado e testado.
