### ISSUE TITLE
Fazer um tópico no Wiki explicando o conceito de barramento de serviço (ESB)

### ISSUE THREAD

**Issue by mhokama** [PPCA2014/ppca_soa#16]
Achei um artigo em http://www.oracle.com/technetwork/articles/soa/ind-soa-esb-1967705.html que explica um pouco mais sobre o conceito de barramento de serviços, e que dá uma visão geral do seu funcionamento, com diagramas de exemplos de utilização (interessante os ícones utilizados). Tenho outros artigos aqui que falam sobre ESB e a idéia seria compilar tudo para montar um referencial teórico para o PPCA_SOA. Acho que consigo entregar até as 12:00 de amanhã.

**Comment by mhokama** [comment]
Outra referência: https://msdn.microsoft.com/pt-br/library/dd920288.aspx#nav3

**Comment by evertonagilar** [comment]
Li a documentação da Oracle, muito interessante.

**Comment by evertonagilar** [comment]
Marçal, você ainda pretende fazer esta Wiki?  

Como tem outras tarefas com mais prioridades, se não tiver começado esta tarefa, acho melhor fechar para nos concentrarmos somente nas tarefas essenciais solicitadas pelo professor.

Pode ser?

**Comment by mhokama** [comment]
Everton, pode deixar essa Issue aberta e associada a mim, mas convergindo com o seu pensamento, estou apoiando na extração da URL. Tô revendo a API do REST e acho que em breve terei uma proposta para apresentar ao grupo.

**Comment by mhokama** [comment]
No final do projeto eu fecho essa Issue.

**Comment by evertonagilar** [comment]
OK

**Comment by celsonjunior** [comment]
Marçal é  uma boa alma. Socorrendo os pobres combalidos.

Encontrei algumas solucoes de parser de query URL no mochiweb. To zolhando
aqui pra ver se ajuda em algo
Em 29/04/2015 16:12, "Everton de Vargas Agilar" notifications@github.com
escreveu:

**Comment by celsonjunior** [comment]
Marçal, o codigo parser URL Query que encontrei no mochiweb é esse:

Em 29 de abril de 2015 16:38, Celson celson.jr@gmail.com escreveu:
