### ISSUE TITLE
Estudar e implementação do mecanismo de Log (Erlang / OTP)

### ISSUE THREAD

**Issue by rbonifacio** [PPCA2014/ppca_soa#17]
Atualmente, a implementação usa um mecanismo de log relativamente primitivo (apenas escreve na tela). Como administrador / usuário da solução, seria interessante o suporte a um mecanismo de Log mais robusto.

**Comment by celsonjunior** [comment]
==>>> (prioridade 2, relevancia 2)

**Comment by evertonagilar** [comment]
Eliene, para implementar esta solução vamos ter que ler os seguintes tópicos do livro:
1. Página 388 do livro que mostra a solução de logger padrão do Erlang;
2. Página 243 Programming with Files caso seja necessário implementar o nosso mecanismo de logger.

**Comment by evertonagilar** [comment]
O livro "Building Web Applications with Erlang" também ensina a usar o logger do OTP na página 30 e 31.

**Comment by evertonagilar** [comment]
Eliene, consegui testar o mecanismo de logger default do Erlang mas acho que vamos precisar desenvolver algo mais simples. 

Este logger do Erlang foge do convencional, gera arquivos binários e possui um aplicativo para (rb) para ler os logs.

Vamos implementar uma processo simples que faz o logger, já eh o suficiente.

**Comment by evertonagilar** [comment]
Eliene, vamos nos reunir hoje às 21:30hs pelo team viewer e vamos revisar  o módulo de logger, para apresentar amanhã para o professor.

**Comment by evertonagilar** [comment]
Você já desenvolveu a função que faz a rotação de logs?

**Comment by Elliene** [comment]
Vamos nos reunir sim. Ja estou quase terminando a função. Porém ainda estou com dificuldade para incluir a data no nome do arquivo.

**Comment by evertonagilar** [comment]
Coloquei o ppca_logger na inicialização do ppca_soa.erl.
