### ISSUE TITLE
Formato de dados

### ISSUE THREAD

**Issue by rbonifacio** [PPCA2014/ppca_soa#18]
Tanto os dados da requisição submetidos via POST ou o retorno das requisições devem ser formatados em JSON. Ou seja, o nosso servidor vai aceitar payloads apenas no formato JSON. É uma simplificação importante para os objetivos da disciplina.

**Comment by evertonagilar** [comment]
Implementação concluída e testada. 

Uma observação quanto a implementação: quando o conteúdo enviado não for JSON será retornado uma mensagem HTTP 415 em formato JSON. Exemplo:
{
    "error": "415",
    "message": "HTTP ERROR 415 - Unsupported Media Type: Tipos dados suportado: JSON"
}

Wiki de teste: https://github.com/PPCA2014/ppca_soa/wiki/Testes-com-a-ferramenta-curl
