### ISSUE TITLE
Efetuar a extração dos argumentos da url

### ISSUE THREAD

**Issue by drausio** [PPCA2014/ppca_soa#19]
Os parametros podem ser da URL ( URL/parametro1/parametro2 ) ou do tipo Query   URL?param=value&param1=value1

**Comment by celsonjunior** [comment]
Envolve query/URL

**Comment by celsonjunior** [comment]
erlang.org/doc/man/http_uri.html#parse-1

Haskell(zip)

**Comment by evertonagilar** [comment]
Referência sobre URI conforme RFC 3986:

https://www.ietf.org/rfc/rfc3986.txt

**Comment by evertonagilar** [comment]
Pessoal, na aula estava dando erro no comando curl com duas query string na URL.

Pelo browser funciona, o motivo eh que a URL pelo curl não tem encode. Esta abaixo tem:

http://localhost:2301/hello_world/2015?id=1&nome=everton%20agilar

Quem for usar o curl preste atenção neste detalhe.

**Comment by evertonagilar** [comment]
No curl mesmo adicionando as aspas duplas o que aconteceu foi isto. Segue log do ppca_server:

Header: 
        "Host":  "localhost"
        "Url":  "/hello_world/2015?id=1&nome='everton"
        "Accept":  "_/_"
        "Metodo":  "POST"
        "Content-Type":  "application/x-www-form-urlencoded"
        "Content-Length":  43
        "Versao_HTTP":  "agilar'"
        "User-Agent":  "curl/7.38.0"
Payload: "{\"telefone\":\"83370683\",\"cidade\":\"Brasilia\"}"

Olha só onde foi parar o agilar ???? no cabeçalho Versao_HTTP!!!!

**Comment by evertonagilar** [comment]
Pessoal, como está o status desta tarefa, vamos ter algo para mostrar amahã para o professor?

**Comment by celsonjunior** [comment]
De minha parte não, Everton

2015-04-29 13:27 GMT-03:00 Everton de Vargas Agilar <
notifications@github.com>:

**Comment by mhokama** [comment]
Pessoal, tô dando uma aprofundada para a fechar como será tratada a URL oriunda do cliente do barramento. Assim que tiver uma idéia final eu posto aqui.

**Comment by celsonjunior** [comment]
Marçal, tá colaborando voluntariamente? Entendi q essa atividade tinha
ficado sob responsabilidade minha, Raphael e FIlipe.

De toda forma, todo auxílio é bem vindo.

Em 29 de abril de 2015 15:49, mhokama notifications@github.com escreveu:

**Comment by evertonagilar** [comment]
Esse é o espirito, também estou pesquisando sobre isso. 

Estou fazendo alguns testes com metaprogramação, módulo RE do Erlang e o gen_server da OTP.

**Comment by raphael-hoed** [comment]
Há um módulo no Github publicado que tem como propósito analisar URL:
https://github.com/bipthelin/mochiweb_util/blob/master/src/mochiweb_util.erl

Como exemplo de código mínimo e simplista:

{"http", "host:port", "/foo", "", "bar?baz"} =
    mochiweb_util:urlsplit("http://host:port/foo#bar?baz").

Parece que essa função urlsplit pode nos ajudar. Vou dar uma olhada

**Comment by celsonjunior** [comment]
Foi esse mesmo que encontrei no mochiweb Drausio. Esotu tentando entender
essa urlsplit tb. Junto com ela tem outra funções, estão no arquivo que
copiei ao Marçal. Amanha te envio

Em 29 de abril de 2015 20:40, Raphael Magalhães Hoed <
notifications@github.com> escreveu:

**Comment by evertonagilar** [comment]
Pessoal, alguém de vocês pode ir hoje as 11h na aula? é o momento para tirar dúvidas.

Eu e a Eliene vamos ir.

**Comment by celsonjunior** [comment]
Everton, qual numero teu telefone?

2015-04-30 9:10 GMT-03:00 Everton de Vargas Agilar <notifications@github.com

**Comment by evertonagilar** [comment]
3107-0052

**Comment by evertonagilar** [comment]
O professor pediu para avisar que nosso encontro será na mesma sala de aula.

**Comment by raphael-hoed** [comment]
O módulo http_uri possui uma função parse capaz de interpretar uma URL. Alguém já tem um nível de compreensão maior da função parse / 2 deste módulo: parse(URI, Options)? 
Já sei que se chamarmos com as opções padrão teremos isso:

parse("http://example.com:8080/path/to/resource?q1=foo&q2=bar#fragmento")
Resultado:

{http,[],"example.com",8080,"/path/to/resource","?q1=foo&q2=bar#fragmento"}

Mas quanto a customização com parse / 2 ainda não compreendi muito bem.

**Comment by raphael-hoed** [comment]
Um exemplo de implementação com parse/1:

-module(url_ppca_soa).
-export([parse_url/0]).
-import(http_uri, [parse/1]).

parse_url() ->
    X = parse("http://teste.com.br:1234/dir/param=value&param1=value1"),
    R= io_lib:format("~p",[X]),
    io:fwrite(lists:flatten(R)),
    true.

Compilando o módulo e executando a função parse_url() teremos algo assim:

{ok,{http,[],"teste.com.br",1234,"/dir/param=value&param1=value1",[]}}true

**Comment by evertonagilar** [comment]
Implementação concluída e testada.

Wiki de teste: https://github.com/PPCA2014/ppca_soa/wiki/Testes-com-a-ferramenta-curl
