### ISSUE TITLE
Implementar arquitetura básica do projeto PPCA_SOA

### ISSUE THREAD

**Issue by evertonagilar** [PPCA2014/ppca_soa#21]
Implementar arquitetura básica do projeto PPCA_SOA.

Arquitetura conforme elaborada em aula.

**Comment by evertonagilar** [comment]
Realizado algumas refatorações necessárias para tornar o código mais limpo.

**Comment by mhokama** [comment]
Havia duas chamadas erradas no código para "ppca_logger:erro_msg". Alterei para o nome correto do módulo "ppca_logger:error_msg"
