### ISSUE TITLE
Erro no rebar compile

### ISSUE THREAD

**Issue by mhokama** [PPCA2014/ppca_soa#25]
Estou tentando fazer o comando rebar compile e está dando o seguinte erro:

C:\temp\ppca_soa>rebar compile
==> ppca_soa (compile)
ERROR: One or more modules listed in ppca_soa.app are not present in ebin/*.beam
:
        \* ppca_soa_app
        \* ppca_soa_sup
ERROR: compile failed while processing C:/temp/ppca_soa: rebar_abort

**Comment by evertonagilar** [comment]
Marçal, de acordo com o arquivo de configuração mantido pelo rebar, os módulos que ele tenta compilar são esses: {modules,[ppca_event_mq,ppca_request,ppca_route,ppca_server,
                        ppca_soa,ppca_soa_app,ppca_soa_sup,ppca_util,
                        test_ppca_route]}]}.

Como ninguém mais reportou este erro, tente isso:

git pull
rebar get-deps
rebar compile

**Comment by evertonagilar** [comment]
Alias, esses módulos  ppca_soa_app e ppca_soa_sup nem foi criado por nós, e sim pelo rebar. Ele criou esses arquivos porque é o padrão em aplicações rebar.

**Comment by mhokama** [comment]
A sequência de comandos que você enviou deu certo, Everton!

C:\temp\ppca_soa>git pull https://github.com/PPCA2014/ppca_soa
From https://github.com/PPCA2014/ppca_soa
- branch            HEAD       -> FETCH_HEAD
  Updating 3d880c6..9df4ae6
  Fast-forward
  README.md               |  69 +++++-----
  ebin/ppca_soa.app       |   5 +-
  include/ppca_config.hrl |  48 +++++++
  rebar.config            |   3 +
  src/aluno.erl           | 214 +++++++++++++++++++++++++++++++
  src/ppca_event_mq.erl   | 214 +++++++++++++++++++------------
  src/ppca_log.erl        |  32 +++++
  src/ppca_logger.erl     | 178 ++++++++++++++++++++++++++
  src/ppca_request.erl    |  89 +++++++++----
  src/ppca_route.erl      | 112 +++++++++++++++++
  src/ppca_server.erl     | 326 ++++++++++++++++++++++++++++++++----------------
  src/ppca_soa.app.src    |  12 ++
  src/ppca_soa.erl        |  36 +++---
  src/ppca_soa_app.erl    |  16 +++
  src/ppca_soa_sup.erl    |  27 ++++
  src/ppca_util.erl       |  28 ++++-
  src/test_ppca_route.erl |  78 ++++++++++++
  start_server.bat        |  22 ++--
  start_server.sh         |   3 +-
  19 files changed, 1229 insertions(+), 283 deletions(-)
  mode change 100644 => 100755 include/ppca_config.hrl
  create mode 100755 rebar.config
  create mode 100755 src/aluno.erl
  create mode 100644 src/ppca_log.erl
  create mode 100755 src/ppca_logger.erl
  mode change 100644 => 100755 src/ppca_request.erl
  create mode 100644 src/ppca_route.erl
  mode change 100644 => 100755 src/ppca_server.erl
  create mode 100644 src/ppca_soa.app.src
  mode change 100644 => 100755 src/ppca_soa.erl
  create mode 100644 src/ppca_soa_app.erl
  create mode 100644 src/ppca_soa_sup.erl
  mode change 100644 => 100755 src/ppca_util.erl
  create mode 100644 src/test_ppca_route.erl
  mode change 100644 => 100755 start_server.bat

C:\temp\ppca_soa>rebar get-deps
==> ppca_soa (get-deps)
Pulling jsx from {git,"https://github.com/talentdeficit/jsx","master"}
Cloning into 'jsx'...
==> jsx (get-deps)

C:\temp\ppca_soa>rebar compile
==> jsx (compile)
Compiled src/jsx_to_term.erl
Compiled src/jsx_verify.erl
Compiled src/jsx_to_json.erl
Compiled src/jsx_encoder.erl
Compiled src/jsx_consult.erl
Compiled src/jsx_config.erl
Compiled src/jsx.erl
Compiled src/jsx_parser.erl
Compiled src/jsx_decoder.erl
==> ppca_soa (compile)
Compiled src/ppca_util.erl
Compiled src/ppca_soa_sup.erl
src/test_ppca_route.erl:52: Warning: variable 'PidModulo' is unused
src/test_ppca_route.erl:69: Warning: variable 'PidModulo' is unused
Compiled src/test_ppca_route.erl
Compiled src/ppca_soa_app.erl
Compiled src/ppca_soa.erl
Compiled src/ppca_server.erl
src/ppca_request.erl:37: Warning: variable 'From1' is unused
src/ppca_request.erl:38: Warning: Non-UTF-8 character(s) detected, but no encodi
ng declared. Encode the file in UTF-8 or add "%% coding: latin-1" at the beginni
ng of the file. Retrying with latin-1 encoding.
src/ppca_request.erl:41: Warning: variable 'From1' is unused
src/ppca_request.erl:45: Warning: variable 'From1' is unused
src/ppca_request.erl:52: Warning: variable 'PidModulo' is unused
src/ppca_request.erl:55: Warning: variable 'From1' is unused
src/ppca_request.erl:59: Warning: variable 'From1' is unused
src/ppca_request.erl:59: Warning: variable 'Method' is unused
Compiled src/ppca_request.erl
Compiled src/ppca_log.erl
Compiled src/ppca_logger.erl
Compiled src/ppca_event_mq.erl
src/ppca_route.erl:2: Warning: Non-UTF-8 character(s) detected, but no encoding
declared. Encode the file in UTF-8 or add "%% coding: latin-1" at the beginning
of the file. Retrying with latin-1 encoding.
src/ppca_route.erl:34: Warning: variable 'HeadrDict' is unused
src/ppca_route.erl:34: Warning: variable 'Router' is unused
src/ppca_route.erl:37: Warning: variable 'Method' is unused
src/ppca_route.erl:37: Warning: variable 'Payload' is unused
src/ppca_route.erl:37: Warning: variable 'Url' is unused
src/ppca_route.erl:40: Warning: variable 'HeadrDict' is unused
src/ppca_route.erl:40: Warning: variable 'Router' is unused
src/ppca_route.erl:43: Warning: variable 'HeadrDict' is unused
src/ppca_route.erl:43: Warning: variable 'Payload' is unused
src/ppca_route.erl:43: Warning: variable 'Router' is unused
src/ppca_route.erl:46: Warning: variable 'Method' is unused
src/ppca_route.erl:46: Warning: variable 'Payload' is unused
src/ppca_route.erl:46: Warning: variable 'Url' is unused
src/ppca_route.erl:100: Warning: variable 'Payload' is unused
src/ppca_route.erl:103: Warning: variable 'Payload' is unused
Compiled src/ppca_route.erl
Compiled src/aluno.erl

C:\temp\ppca_soa>

Valeu!
