### ISSUE TITLE
Desenvolver módulo ppca_dados.erl

### ISSUE THREAD

**Issue by celsonjunior** [PPCA2014/ppca_soa#26]
Desenvolver um módulo no PPCA para receber e tratar um arquivo recebido, que contenha grande volume de dados, utilizando map_reduce.

Por exemplo, podemos receber um documento (uma tese, dissertação) e retornar um resumo das palavras chave do documento. Para contar as palavras, utilizando map_reduce com TF_IDF seria algo como

wc_dir(Dir) ->
 F1 = fun generate_words/2,
 F2 = fun count_words/3,
 Files = … text file name …,
 L1 = phofs:mapreduce(F1, F2, Files),
 reverse(sort(L1)).

**Comment by evertonagilar** [comment]
Eu vou colocar minha experiência na Procergs. Lá nós tinhamos grandes arquivos CSV para fazer import. Fazer isso no cliente é era bastante lento, pois o arquivo precisava ser lido, feito parser e cada linha virava um insert. tudo feito no cliente.

Então, uma solução melhor feito no servidor Oracle era infomar o caminho do arquivo e o arquivo ser processado e importado pelo servidor Oracle e não pelo cliente.

Pergunta: MapReduce poderia ser utilizado para criar um módulo de importação onde informamos o caminho do arquivo e o ppca_dados usa técnicas de MapReduce para particionar o processamento do arquivo e inclusão na base de dados.

OBS.: é apenas uma sugestão para ver se isso é possível de ser feito com MapReduce já que não dediquei um estudo nesta técnica.

**Comment by celsonjunior** [comment]
Everton, vou pesquisar e comento depois. A ideia desse trecho de código é aparentemente a mesma, informar o caminho de uma arquivo a ser processado e o map_reduce faz o processamento de acordo com a técnica definida. 

O exemplo acima é de "resumo" de um texto. O processamento usado é o do TF_IDF que retorna um resumo chave:valor do arquivo. Simplificadamente, no caso chave são as palavras constantes do arquivo e valor é a frequencia dessas palavras.

Se a necessidade for outra, temos que analisar qual a solução mais adequada.

**Comment by felipe-est** [comment]
Celson, a idéia é boa. No meu entendimento, o exemplo do Everton se encaixa no que o código se propõe a fazer. O processamento do arquivo seria feito por "n" processos, onde "n" seria o número de chaves do texto recebido. Vou pesquisar um pouco mais e tentar ver de que forma isso poderia ser incluído na base de dados.
