### ISSUE TITLE
Dificuldade para incluir arquivo.eap no git

### ISSUE THREAD

**Issue by Elliene** [PPCA2014/ppca_soa#27]
Pessoal, estou com dificuldades para incluir o arquivo ppca_soa.eap no git. Alguém pode ajudar?
![erro arquivo eap](https://cloud.githubusercontent.com/assets/11709880/7643842/85510e3a-fa73-11e4-876c-07f71ee1098d.png)

**Comment by evertonagilar** [comment]
Eliene, este erro está ocorrendo porque o seu ambiente de trabalho está desatualizado.  Primeiro sincronize com as alterações do github com este comando:

git pull
rebar get-deps

depois você pode repetir os comandos que estava tentando fazer.

**Comment by Elliene** [comment]
Everton, vou fazer. Porém fiquei com uma dúvida: Quantos git pull tenho que dar no projeto? 
Quando entrei no cmd e abri a pasta do projeto, dei um git pull. Mas coloquei a versão alterada do arquivo ppca_log.erl. Toda vez que faço alguma alteração tenho que executar o comando git pull?

**Comment by Elliene** [comment]
mensagem depois que executei git pull:  already up_to_date

**Comment by evertonagilar** [comment]
Sempre que você quer baixar as últimas atualizaçóes do projeto precisa dar git pull.
