### ISSUE TITLE
Bug: HTTP ERROR 415 - Unsupported Media Type em Windows

### ISSUE THREAD

**Issue by evertonagilar** [PPCA2014/ppca_soa#28]
Bug: Em Windows está ocorrendo erro ao decodificar o JSON.

Erro no console que ocorre:
              Correção HTTP ERROR 415 - Unsupported Media Type em Windows

Analisar a causa do erro pois em Linux este erro não está ocorrendo.

**Comment by evertonagilar** [comment]
Pessoal, eu fiz uma análise em uma máquina Window e descobri o problema:

No Windows não está encontrando as libs para JSON.

Enquanto tento resolver o problema, para corrigir temporariamente devem fazer o seguinte:

Copiar todos os arquivos BEAMS localizado na pasta ppca_soa\deps\jsx\ebin
para dentro de ppca_soa\ebin.

Com isso o ambiente de execução vai encontrar as bibliotecas e vai funcionar a conversão JSON.

Testado com curl e Advanced Rest Client:

![tela server](https://cloud.githubusercontent.com/assets/7144523/7686040/590f5680-fd69-11e4-950d-9bfcfd3e2952.png)

**Comment by Elliene** [comment]
ok, acabei de fazer a transferiria dos arquivos. Deu certo.

**Comment by evertonagilar** [comment]
Concluído. Os scripts start_server foram atualizados.

**Comment by mhokama** [comment]
Depois de copiar os arquivos beam, as pastas /img e /conf para dentro do /ebin, finalmente consegui fazer o servidor funcionar!

---

C:\temp\ppca_soa\ebin>erl
Eshell V6.4  (abort with ^G)
1> l(ppca_soa).
{module,ppca_soa}
2> WebServer = ppca_soa:start(2301).
PPCA->SOA/1.0.0
ppca_info_service iniciado.
To na area 2!!!
ppca_server iniciado.
ppca_favicon_service iniciado.
ppca_catalogo_service iniciado.
helloworld_service iniciado.
Escutando na porta 2301
ok
3> ppca_rota iniciado.
3>
