### ISSUE TITLE
Definição do catálogo de serviços

### ISSUE THREAD

**Issue by Elliene** [PPCA2014/ppca_soa#29]

**Comment by evertonagilar** [comment]
## Definição do Layout

Estou propondo a seguinte definição para o catálogo de serviços:

"Precisamos da sugestão de todos para o layout o mais breve possível pois a Eliene precisa implementar o carregamento do catálogo para próxima aula."

## Segue um exemplo:

```
{
    "comment": "Listagem dos formandos por ano/semestre",
    "owner": "SIGRA",
    "version": "1",
    "url": "/aluno/lista_formandos/",
    "async": "true",
    "url_callback": "/url_de_retorno",
    "type": "GET",
    "querystring": [
        {
            "name": "ano",
            "type": "int",
            "comment": "Ano de pesquisa"
        },
        {
            "name": "semestre",
            "type": "int",
            "comment": "Semestre de pesquisa"
        }
    ]
}
```

Observações

---

1)  Pensei em tipificar o tipo do parâmetro da querystring (int, string, date, bool, etc) para fazer uma validação antes de passar para o serviço mas talvez possamos deixar de fora isso na implementação.

2) A maioria das informações são apenas informativas e não afetam a implementação mas para um catálogo de serviço e para o usuário considero importante, como por exemplo, o comentário do serviço ou do parâmetro de querystring.

**Comment by Elliene** [comment]
pode colocar também a idenfificação da maquina.

**Comment by Elliene** [comment]
Gostei desse material. http://www.w3schools.com/json/

**Comment by mhokama** [comment]
Everton, acho que o layout proposto está bom para o momento. Acredito que iremos evoluir esse layout na medida que os serviços forem sendo utilizados. O importante é que essa definição possa ser alterada sem maiores traumas.

Eliene, acho que no caso de um barramento, não é necessário identificar a máquina que fornece o serviço (pelo menos foi isso que entendi do seu comentário), uma vez que o redirecionamento para o responsável pelo serviço será um processo interno do barramento e transparente para o cliente.

**Comment by evertonagilar** [comment]
É isso ai, o usuário não precisa e não deve saber em qual nó o serviço vai ser processado.

**Comment by Elliene** [comment]
Beleza, e que em alguns exemplo que vi, ele também identificava a máquina. Valeu pela explicação.

**Comment by Elliene** [comment]
Posso trabalhar com a definição proposta? Todos de acordo?

**Comment by evertonagilar** [comment]
Eliene, acabei de comitar o arquivo de catálogo no caminho conf/catalogo.conf.

**Comment by Elliene** [comment]
Vou verificar.

**Comment by Elliene** [comment]
Foi criado o arquivo "catalogo,json" na pasta conf contendo as definições do catalogo.

**Comment by evertonagilar** [comment]
Pessoal, feita uma definição do catálogo de serviço, infelizmente nem todos participaram e a Eliene e eu como auxiliar não teremos tempo para implementar.

Foi feito um commit no ppca_route para alterar de ets para dets. Como já vamos ter um catálogo em formato JSON conforme discutido em aula não precisamos outro mecanismo de persistência.
