### ISSUE TITLE
Definições de Teste

### ISSUE THREAD

**Issue by Elliene** [PPCA2014/ppca_soa#30]

**Comment by Elliene** [comment]
Pessoal, sobre a parte de teste. Já vi alguns vídeos e li a documentação do eram.  Porém tenho dúvidas.  Alguém tem algum material bom?

**Comment by evertonagilar** [comment]
http://learnyousomeerlang.com/eunit

**Comment by evertonagilar** [comment]
Definição concluída e está sendo implementada.
