### ISSUE TITLE
Erro na inicialização do Server no Windows

### ISSUE THREAD

**Issue by mhokama** [PPCA2014/ppca_soa#34]
Everton, depois que dei um git pull, fiz a compilação e quando fui rodar o server, deu um erro:

Eshell V6.4  (abort with ^G)
1> l(ppca_soa).
{module,ppca_soa}
2> WebServer = ppca_soa:start(2301).
PPCA->SOA/1.0.0
ppca_info_service iniciado.
*\* exception exit: {badmatch,{error,enoent}}
     in function  ppca_favicon_service:get_favicon_from_disk/0 (src/ppca_favicon
_service.erl, line 92)
     in call from ppca_favicon_service:init/1 (src/ppca_favicon_service.erl, lin
e 57)
     in call from gen_server:init_it/6 (gen_server.erl, line 306)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 237)
3>

**Comment by evertonagilar** [comment]
Tente estas operações (faça backup do que vc alterou antes)

a) método 1

apaga a pasta ebin
apaga a pasta src

git pull
rebar get-deps
rebar compile

b) método 2

Se não resolver, renomeia a pasta ppca_soa e faça um git clone novamente
para começar de novo de forma limpa
depois execute os comandos:
rebar get-deps
rebar compile

Esta última forma precisa funcionar pois tenho testado em Linux e Windows!

Qualquer coisa me dê acesso remoto com Team Viewer

Att.
Everton de Vargas Agilar
Cel.: (61) 8337-0683

2015-05-28 6:59 GMT-03:00 mhokama notifications@github.com:

**Comment by mhokama** [comment]
Olá Everton,

O método 1 não baixou os arquivos que havia apagado. Segui o método 2 e aparentemente estava tudo ok:

C:\temp\ppca_soa>rebar get-deps
==> ppca_soa (get-deps)
Pulling jsx from {git,"https://github.com/talentdeficit/jsx","master"}
Cloning into 'jsx'...
==> jsx (get-deps)

C:\temp\ppca_soa>rebar compile
==> jsx (compile)
Compiled src/jsx_verify.erl
Compiled src/jsx_to_term.erl
Compiled src/jsx_to_json.erl
Compiled src/jsx_encoder.erl
Compiled src/jsx_consult.erl
Compiled src/jsx_config.erl
Compiled src/jsx_parser.erl
Compiled src/jsx.erl
Compiled src/jsx_decoder.erl
==> ppca_soa (compile)
Compiled src/ppca_util.erl
Compiled src/ppca_soa_sup.erl
Compiled src/ppca_soa_app.erl
src/test_ppca_route.erl:52: Warning: variable 'PidModulo' is unused
src/test_ppca_route.erl:69: Warning: variable 'PidModulo' is unused
Compiled src/test_ppca_route.erl
Compiled src/ppca_soa.erl
src/ppca_route.erl:59: Warning: variable 'HeadrDict' is unused
src/ppca_route.erl:62: Warning: variable 'From' is unused
src/ppca_route.erl:62: Warning: variable 'Method' is unused
src/ppca_route.erl:62: Warning: variable 'Payload' is unused
src/ppca_route.erl:62: Warning: variable 'Url' is unused
src/ppca_route.erl:65: Warning: variable 'HeadrDict' is unused
src/ppca_route.erl:68: Warning: variable 'HeadrDict' is unused
src/ppca_route.erl:68: Warning: variable 'Payload' is unused
src/ppca_route.erl:71: Warning: variable 'From' is unused
src/ppca_route.erl:71: Warning: variable 'Method' is unused
src/ppca_route.erl:71: Warning: variable 'Payload' is unused
src/ppca_route.erl:71: Warning: variable 'Url' is unused
src/ppca_route.erl:81: Warning: variable 'TableRoute' is unused
src/ppca_route.erl:93: Warning: variable 'TableRoute' is unused
src/ppca_route.erl:100: Warning: variable 'TableRoute' is unused
src/ppca_route.erl:114: Warning: variable 'TableRoute' is unused
src/ppca_route.erl:120: Warning: variable 'Payload' is unused
src/ppca_route.erl:129: Warning: variable 'Payload' is unused
src/ppca_route.erl:145: Warning: variable 'TableRoute' is unused
src/ppca_route.erl:150: Warning: function add_rota_servico/2 is unused
src/ppca_route.erl:150: Warning: variable 'Cat' is unused
src/ppca_route.erl:150: Warning: variable 'TableRoute' is unused
Compiled src/ppca_route.erl
Compiled src/ppca_request.erl
Compiled src/ppca_log.erl
Compiled src/ppca_server.erl
Compiled src/ppca_logger.erl
Compiled src/ppca_info_service.erl
Compiled src/ppca_favicon_service.erl
Compiled src/ppca_catalogo.erl
Compiled src/ppca_event_mq.erl
src/ppca_catalogo_service.erl:66: Warning: variable 'HeaderDict' is unused
src/ppca_catalogo_service.erl:67: Warning: variable 'NewState' is unused
Compiled src/ppca_catalogo_service.erl
Compiled src/ppca_auth_user.erl
Compiled src/helloworld_service.erl
Compiled src/aluno.erl

C:\temp\ppca_soa>

Só que quando vou rodar o servidor:

C:\temp\ppca_soa\ebin>erl
Eshell V6.4  (abort with ^G)
1> l(ppca_soa).
{module,ppca_soa}
2> WebServer = ppca_soa:start(2301).
PPCA->SOA/1.0.0
ppca_info_service iniciado.
*\* exception exit: {badmatch,{error,enoent}}
     in function  ppca_favicon_service:get_favicon_from_disk/0 (src/ppca_favicon
_service.erl, line 92)
     in call from ppca_favicon_service:init/1 (src/ppca_favicon_service.erl, lin
e 57)
     in call from gen_server:init_it/6 (gen_server.erl, line 306)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 237)

**Comment by mhokama** [comment]
Tô vendo aqui na lista de inicialização do ppca_soa.erl:

start(Port) -> 
    ppca_logger:start(),
    ppca_logger:info_msg(?SERVER_NAME),
    register(ppca_server, spawn(fun() -> ppca_server:init() end)),
    ppca_info_service:start(),
    ppca_favicon_service:start(),
    ppca_catalogo_service:start(),
    helloworld_service:start(),
    start_listen(Port).

Pela mensagem que aparece inicia o "ppca_info_service", mas está dando algum problema no "ppca_favicon_service"

**Comment by mhokama** [comment]
Debugando um pouco mais parece que o problema é nessa chamada do ppca_favicon_service.erl:

get_favicon_from_disk()->
    {ok, Arquivo} = file:read_file(?FAVICON_PATH),
    Arquivo.

**Comment by evertonagilar** [comment]
Isso, seguir o método 2 então. Testei em duas máquinas Windows e funciona
bem.

Att.
Everton de Vargas Agilar
Cel.: (61) 8337-0683

2015-05-28 18:15 GMT-03:00 mhokama notifications@github.com:

**Comment by mhokama** [comment]
Everton, no meu caso continuou apresentando o problema:

---

C:\temp\ppca_soa\ebin>erl
Eshell V6.4 (abort with ^G)
1> l(ppca_soa).
{module,ppca_soa}
2> WebServer = ppca_soa:start(2301).
PPCA->SOA/1.0.0
ppca_info_service iniciado.
*\* exception exit: {badmatch,{error,enoent}}
in function ppca_favicon_service:get_favicon_from_disk/0 (src/ppca_favicon
_service.erl, line 92)
in call from ppca_favicon_service:init/1 (src/ppca_favicon_service.erl, lin
e 57)
in call from gen_server:init_it/6 (gen_server.erl, line 306)
in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 237)

---

Mas já descobri o que era. Verifiquei no módulo "ppca_favicon_service.erl" que tinha o seguinte trecho:

get_favicon_from_disk()->
    {ok, Arquivo} = file:read_file(?FAVICON_PATH),
    Arquivo.

E verifiquei a definição da constante FAVICON_PATH no arquivo "ppca_soa\include\ppca_config.hrl":

% Local onde está o favicon
-define(FAVICON_PATH, "./img/favicon.ico").

Como este caminho não estava dentro da pasta "/ppca_soa/ebin" (que é de onde estou rodando o servidor), o servidor não estava encontrando o arquivo favicon.ico. Copiei a pasta "/ppca_soa/img" para dentro do "ebin" e passou a funcionar.

**Comment by mhokama** [comment]
Aproveitando o Issue, no meu caso teve que copiar também a pasta "/ppca_soa/conf" para dentro do "ebin" por causa do seguinte erro que passou a ocorrer (não achava o arquivo "/conf/catalogo.json"):

---

C:\temp\ppca_soa\ebin>erl
Eshell V6.4  (abort with ^G)
1> l(ppca_soa).
{module,ppca_soa}
2> WebServer = ppca_soa:start(2301).
PPCA->SOA/1.0.0
ppca_info_service iniciado.
To na area 2!!!
ppca_server iniciado.
ppca_favicon_service iniciado.
*\* exception exit: {badmatch,{error,enoent}}
     in function  ppca_catalogo_service:do_get_catalogo_from_disk/0 (src/ppca_ca
talogo_service.erl, line 106)
     in call from ppca_catalogo_service:do_get_catalogo/0 (src/ppca_catalogo_ser
vice.erl, line 100)
     in call from ppca_catalogo_service:init/1 (src/ppca_catalogo_service.erl, l
ine 59)
     in call from gen_server:init_it/6 (gen_server.erl, line 306)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 237)
3>

---
