### ISSUE TITLE
ppca_request:executa_servico não encaminha o Payload?

### ISSUE THREAD

**Issue by mhokama** [PPCA2014/ppca_soa#35]
Verifiquei que quando o usuário chama a rota "/autentica" no cliente, o módulo "ppca_request:processa_servico" chama "ppca_request:executa_servico" no seguinte trecho:

```
    {ok, Target} -> 
        case executa_servico(Target, [HeaderDict, From]) of
```

e o executa_servico irá chamar o módulo que estou desenvolvendo (ppca_auth_user:autentica). Eu preciso extrair do Payload as chaves/valor do usuário e senha, mas isso não está sendo encaminhado pelo executa_servico. Onde o meu módulo enxerga o Payload?

**Comment by evertonagilar** [comment]
A assinatura do método deve ser assim:

autentica(HeaderDict, Payload, From) ->
    io:format("Paylod autentica: ~p\n\n", [Payload]),
        ...

Para este e outros problemas envolvendo JSON, fazer estes comandos:
git pull
rebar get-deps
rebar compile
./start_server.sh

**Comment by evertonagilar** [comment]
Ver solução na issue.

Att.
Everton de Vargas Agilar
Cel.: (61) 8337-0683

Em 4 de junho de 2015 22:44, mhokama notifications@github.com escreveu:
