### ISSUE TITLE
Revisar a RFC 2616 para analizar os códigos de retornos que devemos tratar

### ISSUE THREAD

**Issue by evertonagilar** [PPCA2014/ppca_soa#4]
Tarefa 02: Como qualquer servidor HTTP, precisamos analisar quais os códigos de retorno HTTP devemos tratar em nosso servidor.

RFC: https://www.ietf.org/rfc/rfc2616.txt

Inserir um link na wiki e descrever os codigos que devem ser tratados com uma breve explicação sobre cada um.

**Comment by raphael-hoed** [comment]
Como contribuição para leitura existe uma tradução para RFC 2616 disponível no endereço:

http://www.nacaolivre.com.br/open-source/traducao-rfc-2616/

Irei estudar a documentação e tentar criar um catálogo de códigos de retorno que seriam de conveniente uso em nosso servidor.

**Comment by evertonagilar** [comment]
Acho que nem todos conhecem o protocolo HTTP, você poderia fazer uma apresentação dele na aula.

**Comment by raphael-hoed** [comment]
Perfeito. Posso sim.

**Comment by evertonagilar** [comment]
Raphael, preciso saber se o método GET pode ter payload? e se pode, se é uma boa prática ter/ler o payload de um GET.

Estou com esta dúvida. No método POST é obrigatório enviar o payload mas no GET acho que não pode. O que diz a RFC?

**Comment by raphael-hoed** [comment]
Everton, de acordo com a leitura que fiz da RFC 2616 o método pode ter payload. Isso pode ser feito em consultas. Embora a maioria dos navegadores tenha dificuldade em lidar com URLs que excedem 2000 caracteres pelo que vi a respeito.

**Comment by evertonagilar** [comment]
ok

**Comment by raphael-hoed** [comment]
Descrição da RFC 7231 quanto aos métodos:

HEAD - No defined body semantics.
GET - No defined body semantics.
PUT - Body supported.
POST - Body supported.
DELETE - No defined body semantics.
TRACE - Body not supported.
OPTIONS - Body supported but no semantics on usage (maybe in the future).
CONNECT - No defined body semantics

**Comment by evertonagilar** [comment]
ok!
