### ISSUE TITLE
Desenvolver wiki da arquitetura do PPCA_SOA

### ISSUE THREAD

**Issue by evertonagilar** [PPCA2014/ppca_soa#6]
Tarefa 04: Inserir na wiki um link para documentar a arquitetura do nosso projeto.

Pela exposição da aula de sexta já é possível documentar uma boa parte do servidor. Conforme o software vai sendo desenvolvido, o responsável vai documentando.

Para aprender a fazer wiki pode olhar as que eu já criei.

**Comment by Elliene** [comment]
Temos que validar o desenho da arquitetura.

**Comment by evertonagilar** [comment]
Sim, vamos fazer isso na segunda-feira. Por enquanto pode documentar o que foi exposto na aula sexta.

**Comment by Elliene** [comment]
Tudo bem. Ja estou fazendo isso.
Em 19/04/2015 00:19, "Everton de Vargas Agilar" notifications@github.com
escreveu:
