### ISSUE TITLE
Desenvolver funções encode/decode URL no módulo ppca_util.erl

### ISSUE THREAD

**Issue by evertonagilar** [PPCA2014/ppca_soa#9]
Tarefa: Desenvolver no módulo ppca_util.erl duas funções para fazer encode e decode de dados HTML.

É necessário pois o payload vem codificado.

Ajuda: http://www.w3schools.com/tags/ref_urlencode.asp

**Comment by evertonagilar** [comment]
Veja o módulo http_uri: http://erlang.org/doc/man/http_uri.html

**Comment by Elliene** [comment]
Estou implementando o encode / decode em erlang. Talvez termino amanhã e entrego a versão.

**Comment by evertonagilar** [comment]
Pelo que vi, o módulo http_uri já tens esta função. Verifique se pode ser utilizado.

**Comment by Elliene** [comment]
Vi o modulo Http_uri, porém ainda tenho muita dificuldade pra entender a linguagem e o funcionamento dele.

**Comment by evertonagilar** [comment]
Com o estudo que fizemos ontem, você tem condições de chamar as funções deste módulo pelo prompt do erl.

**Comment by evertonagilar** [comment]
Tarefa encerrada pois estas funções já estão disponíveis na biblioteca http_uri da OTP.
